# Generated by Django 5.1.3 on 2025-04-29 12:23

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Passport', 'Passport'), ('National ID Card', 'National ID Card'), ('Driving License', 'Driving License'), ('Residency Permit', 'Residency Permit'), ('Other', 'Other')], max_length=32)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('expiration', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('email', models.EmailField(db_index=True, max_length=256)),
                ('email_is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birthdate', models.DateField(null=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('course', models.CharField(choices=[('Engineering', 'Engineering'), ('Architecture', 'Architecture'), ('Design', 'Design')], max_length=32, null=True)),
                ('phone_prefix', models.CharField(max_length=10, null=True)),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('whatsapp_prefix', models.CharField(max_length=10, null=True)),
                ('whatsapp_number', models.PositiveIntegerField(null=True)),
                ('person_code', models.PositiveIntegerField(db_index=True, null=True)),
                ('domicile', models.CharField(max_length=256, null=True)),
                ('is_esner', models.BooleanField(default=False)),
                ('matricola_number', models.IntegerField(db_index=True, null=True)),
                ('matricola_expiration', models.DateField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical profile',
                'verbose_name_plural': 'historical profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('email_is_verified', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('birthdate', models.DateField(null=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('course', models.CharField(choices=[('Engineering', 'Engineering'), ('Architecture', 'Architecture'), ('Design', 'Design')], max_length=32, null=True)),
                ('phone_prefix', models.CharField(max_length=10, null=True)),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('whatsapp_prefix', models.CharField(max_length=10, null=True)),
                ('whatsapp_number', models.PositiveIntegerField(null=True)),
                ('person_code', models.PositiveIntegerField(null=True, unique=True)),
                ('domicile', models.CharField(max_length=256, null=True)),
                ('is_esner', models.BooleanField(default=False)),
                ('matricola_number', models.IntegerField(null=True, unique=True)),
                ('matricola_expiration', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
